// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: ecdsa-presign.proto

package presign

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
// Represents a P2P message sent to each party during Round 1 of the ECDSA TSS presign protocol.
type PresignRound1Message1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C               []byte   `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	RangeProofAlice [][]byte `protobuf:"bytes,2,rep,name=range_proof_alice,json=rangeProofAlice,proto3" json:"range_proof_alice,omitempty"`
}

func (x *PresignRound1Message1) Reset() {
	*x = PresignRound1Message1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecdsa_presign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresignRound1Message1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignRound1Message1) ProtoMessage() {}

func (x *PresignRound1Message1) ProtoReflect() protoreflect.Message {
	mi := &file_ecdsa_presign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignRound1Message1.ProtoReflect.Descriptor instead.
func (*PresignRound1Message1) Descriptor() ([]byte, []int) {
	return file_ecdsa_presign_proto_rawDescGZIP(), []int{0}
}

func (x *PresignRound1Message1) GetC() []byte {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *PresignRound1Message1) GetRangeProofAlice() [][]byte {
	if x != nil {
		return x.RangeProofAlice
	}
	return nil
}

//
// Represents a BROADCAST message sent to all parties during Round 1 of the ECDSA TSS presign protocol.
type PresignRound1Message2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *PresignRound1Message2) Reset() {
	*x = PresignRound1Message2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecdsa_presign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresignRound1Message2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignRound1Message2) ProtoMessage() {}

func (x *PresignRound1Message2) ProtoReflect() protoreflect.Message {
	mi := &file_ecdsa_presign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignRound1Message2.ProtoReflect.Descriptor instead.
func (*PresignRound1Message2) Descriptor() ([]byte, []int) {
	return file_ecdsa_presign_proto_rawDescGZIP(), []int{1}
}

func (x *PresignRound1Message2) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

var File_ecdsa_presign_proto protoreflect.FileDescriptor

var file_ecdsa_presign_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2d, 0x70, 0x72, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x73, 0x69, 0x67, 0x6e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x12, 0x0c,
	0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x63, 0x12, 0x2a, 0x0a, 0x11,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x61, 0x6c, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x41, 0x6c, 0x69, 0x63, 0x65, 0x22, 0x37, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x31, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x65, 0x63, 0x64, 0x73, 0x61, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ecdsa_presign_proto_rawDescOnce sync.Once
	file_ecdsa_presign_proto_rawDescData = file_ecdsa_presign_proto_rawDesc
)

func file_ecdsa_presign_proto_rawDescGZIP() []byte {
	file_ecdsa_presign_proto_rawDescOnce.Do(func() {
		file_ecdsa_presign_proto_rawDescData = protoimpl.X.CompressGZIP(file_ecdsa_presign_proto_rawDescData)
	})
	return file_ecdsa_presign_proto_rawDescData
}

var file_ecdsa_presign_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ecdsa_presign_proto_goTypes = []interface{}{
	(*PresignRound1Message1)(nil), // 0: PresignRound1Message1
	(*PresignRound1Message2)(nil), // 1: PresignRound1Message2
}
var file_ecdsa_presign_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ecdsa_presign_proto_init() }
func file_ecdsa_presign_proto_init() {
	if File_ecdsa_presign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ecdsa_presign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresignRound1Message1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ecdsa_presign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresignRound1Message2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ecdsa_presign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ecdsa_presign_proto_goTypes,
		DependencyIndexes: file_ecdsa_presign_proto_depIdxs,
		MessageInfos:      file_ecdsa_presign_proto_msgTypes,
	}.Build()
	File_ecdsa_presign_proto = out.File
	file_ecdsa_presign_proto_rawDesc = nil
	file_ecdsa_presign_proto_goTypes = nil
	file_ecdsa_presign_proto_depIdxs = nil
}
